import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Financial Scope",
  description: "Generated by create next app",
};

const customFont = localFont({
  src: [
    {
      path: "../../public/fonts/HYQiHei-55S.ttf",
      weight: "300",
      style: "normal",
    },
  ],
});

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body className={`${customFont.className} h-screen w-screen`}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
